services:
  # reverse-proxy:
  #   image: "traefik:v3.2"
  #   ports:
  #     - "443:443"
  #     - "80:80"
  frontend:
    build: "frontend"
    # ports:
    #   - "80:80"
    depends_on:
      - "backend"
    networks:
      - "traefik-network"
      - "frontend"
  backend:
    build: "backend"
    ports:
      - "3000:3000"
    environment:
      STORAGE: "mysql"
      MYSQL_HOST: "database"
      MYSQL_DB: "mydb"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PWD: "${MYSQL_PASSWORD}"
    # env_file:
    #   - "./backend/.env"
    depends_on:
      - "database"
    networks:
      - "frontend"
      - "backend"
      # - "traefik-network"
  database:
    image: "mysql:8.0.29-debian"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    # env_file:
    #   - "./database/.env"
    volumes:
      - "./sqlScripts/:/docker-entrypoint-initdb.d/"
      - "dbdata:/var/lib/mysql"
    networks:
      - "backend"
      # - "traefik-network"
volumes:
  dbdata:
networks:
  frontend:
  backend:
  traefik-network:
    external: true
