http:
  routers:
    # to-application:
    #   rule: "Host(`application.188.245.228.109`)" # && PathPrefix(`/todo/`)"
    #   service: frontend
    to-application:
      rule: "Host(`188.245.228.109`)" # && PathPrefix(`/todo/`)"
      service: frontend
  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:80/