http:
  routers:
    to-traefik:
      rule: "Host(`www.traefik.klaasenlowie.live`)"
      service: reverse-proxy
      entrypoints: websecure
      tls:
        certresolver: myresolver
    to-application:
      rule: "Host(`www.todo.klaasenlowie.live`)"
      service: frontend
      entrypoints: websecure
      tls:
        certresolver: myresolver
    # api:
    #   rule: "Host(`www.klaasenlowie.live`) && PathPrefix(`/api`)"
    #   service: backend
    to-jenkins:
      rule: "Host(`www.jenkins.klaasenlowie.live`)"
      service: jenkins
      entrypoints: websecure
      tls:
        certresolver: myresolver
  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:80/
    reverse-proxy:
      loadBalancer:
        servers:
        - url: http://reverse-proxy:8080/
    jenkins:
      loadBalancer:
        servers:
        - url: http://jenkins:8080/