http:
  routers:
    to-service:
      rule: "Host(`example.localhost`) && PathPrefix(`/service/`)"
      service: whoami
  services:
    serviceNaam:
      loadBalancer:
        servers:
        - url: http://dockerContainer:80