http:
  routers:
    to-application:
      rule: "Host(`application.localhost`)" # && PathPrefix(`/todo/`)"
      service: frontend
  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:80/