http:
  routers:
    # to-traefik:
    #   rule: "Host(`188.245.228.109`) && PathPrefix(`/traefik`)"
    #   service: reverse-proxy
    to-application:
      rule: "Host(`188.245.228.109`)"
      # rule: "Host(`188.245.228.109`) && PathPrefix(`/todo/`)"
      service: frontend
    # api:
    #   rule: "Host(`188.245.228.109`) && PathPrefix(`/api/`)"
    #   service: backend
    # to-jenkins:
    #   rule: "Host(`188.245.228.109`)"
    #   # rule: "Host(`188.245.228.109`) && PathPrefix(`/jenkins/`)"
    #   service: jenkins
    webui:
      # rule: "Host(`188.245.228.109`) && 
      rule: "PathPrefix(`/dashboard/`)"
      service: reverse-proxy
  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:80/
    reverse-proxy:
      loadBalancer:
        servers:
        - url: http://reverse-proxy:8080/
    # jenkins:
    #   loadBalancer:
    #     servers:
    #     - url: http://jenkins:8080/
    # backend:
    #   loadBalancer:
    #     servers:
    #     - url: http://backend:3000/api/