http:
  routers:
    # to-traefik:
    #   rule: "Host(`188.245.228.109`) && PathPrefix(`/traefik`)"
    #   service: reverse-proxy
    to-application:
      rule: "Host(`188.245.228.109`) && PathPrefix(`/todo`)"
      service: frontend
    to-jenkins:
      rule: "Host(`188.245.228.109`)"
      # rule: "Host(`188.245.228.109`) && PathPrefix(`/login`)"
      service: jenkins
    webui:
      rule: "PathPrefix(`/dashboard`)"
      service: reverse-proxy
    api:
      rule: "PathPrefix(`/api`)"
      service: reverse-proxy
  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:80/
    reverse-proxy:
      loadBalancer:
        servers:
        - url: http://reverse-proxy:8080/
    jenkins:
      loadBalancer:
        servers:
        - url: http://jenkins:8080/