entryPoints:
  web:
    address: :80
  websecure:
    address: :443
api:
  insecure: false
providers:
  docker: {}
  file:
    filename: /etc/traefik/config.yml
certificatesresolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: lowie.klaasen@gmail.com
      storage: /letsencrypt/acme.json